---
name: solidity-language-server
description: Solidity language server by NomicFoundation
homepage: https://github.com/NomicFoundation/hardhat-vscode
licenses:
  - proprietary
languages:
  - Solidity
categories:
  - LSP

source:
  id: pkg:npm/@ignored/solidity-language-server@0.6.14

bin:
  solidity-ls: npm:@ignored/solidity-language-server
