---
name: nomicfoundation-solidity-language-server
description: Solidity language server by NomicFoundation
homepage: https://github.com/NomicFoundation/hardhat-vscode
licenses:
  - MIT
languages:
  - Solidity
categories:
  - LSP

source:
  id: pkg:npm/%40ignored/solidity-language-server@0.6.14

bin:
  nomicfoundation-solidity-language-server: npm:nomicfoundation-solidity-language-server
